<?php
/**
 * Created by PhpStorm.
 * User: 13148872522
 * Date: 2019/4/24
 * Time: 16:57
 */

namespace app\models;

use Yii;
use yii\base\Model;



class BaseModel extends Model
{

    protected $table ='';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function getOne(){

    }

}